services:
  load-balancer:
    image: nginx:latest
    container_name: nginx-proxy
    networks:
      - backend
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "15MB"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1

  database: 
    image: redis:alpine
    container_name: database
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "220MB"

  api1:
    build: .
    restart: always
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - api/node_modules/
            - database/data/
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "500MB"
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - database

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true